spring:
  application:
    name: eureka-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/  #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔
#    register-with-eureka: false   # 表示是否将自己注册到Eureka Server，默认为true
#    fetch-registry: false         # 表示是否从Eureka Server获取注册信息，默认为true
server:
  port: 8000